import os

import pymongo

client = pymongo.MongoClient('localhost', 27017)
# Connect to our database
db = client['gks_bot_db']
tanks = db['tanks']
oil_actions = db['oil_actions']


TANKS = [
    {
        'type': 'ГПА',
        'num': '52',
        'tank': 'Д',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Маслобак двигателя ГПА 52',
    },
    {
        'type': 'ГПА',
        'num': '52',
        'tank': 'Н',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 5,
        'description': 'Маслобак нагнетателя ГПА 52',
    },
    {
        'type': 'ГПА',
        'num': '53',
        'tank': 'Д',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Маслобак двигателя ГПА 53',
    },
    {
        'type': 'ГПА',
        'num': '53',
        'tank': 'Н',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 5,
        'description': 'Маслобак нагнетателя ГПА 53',
    },
    {
        'type': 'ГПА',
        'num': '54',
        'tank': 'Д',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Маслобак двигателя ГПА 54',
    },
    {
        'type': 'ГПА',
        'num': '54',
        'tank': 'Н',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 5,
        'description': 'Маслобак нагнетателя ГПА 54',
    },
    {
        'type': 'ГПА',
        'num': '55',
        'tank': 'Д',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Маслобак двигателя ГПА 55',
    },
    {
        'type': 'ГПА',
        'num': '55',
        'tank': 'Н',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 5,
        'description': 'Маслобак нагнетателя ГПА 55',
    },
    {
        'type': 'ГПА',
        'num': '61',
        'tank': 'Д',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Маслобак двигателя ГПА 61',
    },
    {
        'type': 'ГПА',
        'num': '61',
        'tank': 'Н',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 5,
        'description': 'Маслобак нагнетателя ГПА 61',
    },
    {
        'type': 'ГПА',
        'num': '62',
        'tank': 'Д',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Маслобак двигателя ГПА 62',
    },
    {
        'type': 'ГПА',
        'num': '62',
        'tank': 'Н',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 5,
        'description': 'Маслобак нагнетателя ГПА 62',
    },
    {
        'type': 'ГПА',
        'num': '63',
        'tank': 'Д',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Маслобак двигателя ГПА 63',
    },
    {
        'type': 'ГПА',
        'num': '63',
        'tank': 'Н',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 5,
        'description': 'Маслобак нагнетателя ГПА 63',
    },
    {
        'type': 'ГПА',
        'num': '64',
        'tank': 'Д',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Маслобак двигателя ГПА 64',
    },
    {
        'type': 'ГПА',
        'num': '64',
        'tank': 'Н',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 5,
        'description': 'Маслобак нагнетателя ГПА 64',
    },
    {
        'type': 'ГПА',
        'num': '65',
        'tank': 'Д',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Маслобак двигателя ГПА 65',
    },
    {
        'type': 'ГПА',
        'num': '65',
        'tank': 'Н',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 5,
        'description': 'Маслобак нагнетателя ГПА 65',
    },
    {
        'type': 'МХ',
        'num': '6',
        'tank': '1',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Маслобак №1 маслохозяйства КЦ-6',
    },
    {
        'type': 'МХ',
        'num': '6',
        'tank': '2',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Маслобак №2 маслохозяйства КЦ-6',
    },
    {
        'type': 'МХ',
        'num': '6',
        'tank': '3',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Маслобак №3 маслохозяйства КЦ-6',
    },
    {
        'type': 'МХ',
        'num': '6',
        'tank': '4',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Маслобак №4 маслохозяйства КЦ-6',
    },
    {
        'type': 'ГСМ',
        'num': '5',
        'tank': '1',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Емкость №1 склада ГСМ КЦ-5',
    },
    {
        'type': 'ГСМ',
        'num': '5',
        'tank': '6',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Емкость №6 склада ГСМ КЦ-5',
    },
    {
        'type': 'ГСМ',
        'num': '5',
        'tank': '2',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Емкость №2 склада ГСМ КЦ-5',
    },
    {
        'type': 'ГСМ',
        'num': '5',
        'tank': '3',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Емкость №3 склада ГСМ КЦ-5',
    },
    {
        'type': 'ГСМ',
        'num': '5',
        'tank': '4',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Емкость №4 склада ГСМ КЦ-5',
    },
    {
        'type': 'ГСМ',
        'num': '5',
        'tank': '5',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Емкость №5 склада ГСМ КЦ-5',
    },
    {
        'type': 'БПМ',
        'num': '2',
        'tank': '1',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Емкость №1 БПМ№2 КЦ-5',
    },
    {
        'type': 'БПМ',
        'num': '2',
        'tank': '2',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Емкость №2 БПМ№2 КЦ-5',
    },
    {
        'type': 'БПМ',
        'num': '3',
        'tank': '1',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Емкость №1 БПМ№3 КЦ-5',
    },
    {
        'type': 'БПМ',
        'num': '3',
        'tank': '2',
        'cur_volume': '0',
        'last_update': '',
        'calibration': 1,
        'description': 'Емкость №2 БПМ№3 КЦ-5',
    },
]

for tank in TANKS:
    tanks.insert_one({
        'type': tank.get('type'),
        'num': tank.get('num'),
        'tank': tank.get('tank'),
        'cur_volume': int(tank.get('cur_volume')),
        'last_update': tank.get('last_update'),
        'description': tank.get('description'),
    })
